# 网站基本信息
title: "我的个人网站"       # 网站标题
description: "欢迎访问我的GitHub主页"  # 网站描述
url: "https://pmspku.github.io"  # 你的GitHub Pages网址
baseurl: ""  # 如果网站不在根目录（如子路径），需填写子路径（如 "/blog"）

# Jekyll 设置
theme: minima  # 使用的主题（GitHub Pages默认支持minima）
plugins:       # 启用的插件
  - jekyll-feed

# 作者信息
author:
  name: "pengmingsha"
  email: "pms752493859@163.com"
  github: "pmspku"
